name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p
    - name: Show Build Settings
      run: xcodebuild -project Rawg.io.xcodeproj -scheme Rawg.io -showBuildSettings
    - name: Show Build SDK
      run: xcodebuild -project Rawg.io.xcodeproj -scheme Rawg.io -showsdks
    - name: Show Available Destinations
      run: xcodebuild -project Rawg.io.xcodeproj -scheme Rawg.io -showdestinations
    - name: Swift Linting
      run: swiftlint --config .swiftlint.yml
    - name: Build Project
      run: xcodebuild build -project Rawg.io.xcodeproj -configuration Debug -scheme Rawg.io -allowProvisioningUpdates -showBuildTimingSummary
